name: Publish Package to npmjs

on:
  push:
    branches: [main] # main 分支有 push 时触发
    paths-ignore:   # 下列文件的变更不触发部署，可以自行添加
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # 下载源码
      # 这一步就是检出你的仓库并下载里面的代码到runner中,actions/checkout@v2是官方自己造的轮子，直接拿来用就行
      - name: Checkout
        uses: actions/checkout@v2

      # 打包构建
      - name: Build
        uses: actions/setup-node@master
        with:
          node-version: '18.16.0'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install # 安装依赖
      - run: npm run build # 打包
      - run: npm run docs:build # 打包docs
      - run: npm publish
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # 部署到 GitHub pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3 # 使用部署到 GitHub pages 的 action
        with:
          publish_dir: ./docs/.vuepress/dist # 部署打包后的 dist 目录
          github_token: ${{ secrets.DEPLOY_SECDOCS_DEPLOY_SECRETRET }} # secret 名
          user_name: ${{ secrets.MY_USER_NAME }}
          user_email: ${{ secrets.MY_USER_EMAIL }}
          commit_message: 自动部署 # 部署时的 git 提交信息，自由填写